# Generated by Django 5.2.3 on 2025-07-02 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='process.devicetype')),
            ],
            options={
                'unique_together': {('device_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, unique=True)),
                ('order_type', models.CharField(choices=[('BROKER', 'Broker'), ('RETAIL', 'Retail'), ('MARKETPLACE', 'Marketplace')], max_length=20)),
                ('net_price_fw', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=10)),
                ('logistics_cost_fw', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency_rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('net_price_chf', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('total_quantity', models.PositiveIntegerField(editable=False)),
                ('reserved_quantity', models.PositiveIntegerField()),
                ('quantity_retail', models.PositiveIntegerField()),
                ('quantity_broker', models.PositiveIntegerField()),
                ('quantity_marketplace', models.PositiveIntegerField()),
                ('order_date', models.DateField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('securaze_possible', models.BooleanField()),
                ('dataset_received', models.BooleanField(default=False)),
                ('dataset_imported', models.BooleanField(default=False)),
                ('test_required', models.BooleanField()),
                ('cleaning_choice', models.CharField(choices=[('NO', 'Nein'), ('MINIMAL', 'Ja, minimal'), ('FULL', 'Ja, voll')], max_length=20)),
                ('wipe_method', models.CharField(choices=[('NO', 'Nein'), ('SMART_ERASURE', 'Smart Erasure'), ('DATA_CLEAR', 'Data Clear')], max_length=20)),
                ('packaging', models.CharField(choices=[('LARGE_BOX', 'Grosskarton'), ('FOLDING_BOX', 'Faltkarton')], max_length=50)),
                ('sell_price_net', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('braendi_required', models.BooleanField()),
                ('braendi_notified_at', models.DateField(blank=True, null=True)),
                ('braendi_delivered_at', models.DateField(blank=True, null=True)),
                ('braendi_collected_at', models.DateField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='process.customer')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='process.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='OrderPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_number', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
                ('ram', models.CharField(max_length=50)),
                ('processor', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='process.devicemodel')),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='process.devicetype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='process.order')),
            ],
            options={
                'ordering': ['position_number'],
                'unique_together': {('order', 'position_number')},
            },
        ),
    ]
