# Generated by Django 5.2.3 on 2025-07-08 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gerätetyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Gerätetyp')),
            ],
            options={
                'verbose_name': 'Gerätetyp',
                'verbose_name_plural': 'Gerätetypen',
            },
        ),
        migrations.CreateModel(
            name='Lieferant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=50, unique=True, verbose_name='Lieferantennummer')),
                ('name', models.CharField(max_length=200, verbose_name='Lieferant')),
            ],
            options={
                'verbose_name': 'Lieferant',
                'verbose_name_plural': 'Lieferanten',
            },
        ),
        migrations.CreateModel(
            name='Gerätemodell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Modellbezeichnung')),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelle', to='process.gerätetyp', verbose_name='Gerätetyp')),
            ],
            options={
                'verbose_name': 'Gerätemodell',
                'verbose_name_plural': 'Gerätemodelle',
                'unique_together': {('typ', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Lieferung',
            fields=[
                ('liefernummer', models.AutoField(primary_key=True, serialize=False, verbose_name='Liefernummer')),
                ('bestelldatum', models.DateField(verbose_name='Bestelldatum')),
                ('erwartetes_datum', models.DateField(blank=True, null=True, verbose_name='Erwartetes Ankunftsdatum')),
                ('gesamtmenge', models.PositiveIntegerField(verbose_name='Menge Total')),
                ('effektives_datum', models.DateField(blank=True, null=True, verbose_name='Effektives Ankunftsdatum')),
                ('kommentar', models.TextField(blank=True, verbose_name='Kommentar')),
                ('lieferant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='process.lieferant', verbose_name='Lieferant')),
            ],
            options={
                'verbose_name': 'Lieferauftrag',
                'verbose_name_plural': 'Lieferaufträge',
                'ordering': ['liefernummer'],
            },
        ),
        migrations.CreateModel(
            name='Lieferungsposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionsnummer', models.PositiveIntegerField(verbose_name='Positionsnummer')),
                ('farbe', models.CharField(max_length=50, verbose_name='Farbe')),
                ('speicher', models.CharField(max_length=50, verbose_name='Speicher')),
                ('ram', models.CharField(max_length=50, verbose_name='RAM')),
                ('prozessor', models.CharField(max_length=100, verbose_name='Prozessor')),
                ('zustand', models.CharField(max_length=100, verbose_name='Zustand')),
                ('menge', models.PositiveIntegerField(verbose_name='Menge')),
                ('geraetemodell', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='process.gerätemodell', verbose_name='Gerätemodell')),
                ('geraetetyp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='process.gerätetyp', verbose_name='Gerätetyp')),
                ('lieferung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionen', to='process.lieferung', verbose_name='Lieferung')),
            ],
            options={
                'verbose_name': 'Lieferungsposition',
                'verbose_name_plural': 'Lieferungspositionen',
                'ordering': ['positionsnummer'],
                'unique_together': {('lieferung', 'positionsnummer')},
            },
        ),
    ]
