# Generated by Django 5.2.3 on 2025-07-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='net_price_chf',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_quantity',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
