# Generated by Django 5.2.3 on 2025-07-03 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lieferung',
            fields=[
                ('liefernummer', models.AutoField(primary_key=True, serialize=False, verbose_name='Liefernummer')),
                ('bestelldatum', models.DateField(verbose_name='Bestelldatum')),
                ('erwartetes_datum', models.DateField(verbose_name='Erwartetes Ankunftsdatum')),
                ('effektives_datum', models.DateField(blank=True, null=True, verbose_name='Effektives Ankunftsdatum')),
                ('lieferant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='process.lieferant', verbose_name='Lieferant')),
            ],
            options={
                'verbose_name': 'Lieferauftrag',
                'verbose_name_plural': 'Lieferaufträge',
                'ordering': ['liefernummer'],
            },
        ),
    ]
