# Generated by Django 5.2.3 on 2025-07-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_lieferung'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lieferung',
            options={},
        ),
        migrations.AddField(
            model_name='lieferung',
            name='gesamtmenge',
            field=models.PositiveIntegerField(default=0, verbose_name='Menge Total'),
            preserve_default=False,
        ),
    ]
