# Generated by Django 5.2.3 on 2025-07-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_lieferung_liefertermin'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieferung',
            name='confirmed_menge',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
