# Generated by Django 5.2.3 on 2025-07-08 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_alter_lieferung_options_lieferung_gesamtmenge'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lieferung',
            options={'ordering': ['liefernummer'], 'verbose_name': 'Lieferauftrag', 'verbose_name_plural': 'Lieferaufträge'},
        ),
    ]
