# Generated by Django 5.2.3 on 2025-07-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_lieferung_confirmed_menge'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieferungsposition',
            name='auftragsart',
            field=models.CharField(blank=True, max_length=200, verbose_name='Auftragsart'),
        ),
        migrations.AddField(
            model_name='lieferungsposition',
            name='braendi',
            field=models.CharField(blank=True, max_length=50, verbose_name='Braendi'),
        ),
        migrations.AddField(
            model_name='lieferungsposition',
            name='datensatz_eingepflegt',
            field=models.CharField(blank=True, max_length=50, verbose_name='Datensatz eingepflegt'),
        ),
        migrations.AddField(
            model_name='lieferungsposition',
            name='datensatz_erhalten',
            field=models.CharField(blank=True, max_length=50, verbose_name='Datensatz erhalten'),
        ),
        migrations.AddField(
            model_name='lieferungsposition',
            name='ek_netto_chf',
            field=models.CharField(blank=True, max_length=100, verbose_name='EK netto CHF'),
        ),
        migrations.AddField(
            model_name='lieferungsposition',
            name='ek_netto_fw',
            field=models.CharField(blank=True, max_length=100, verbose_name='EK netto FW'),
        ),
        migrations.AddField(
            model_name='lieferungsposition',
            name='kunde',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kunde'),
        ),
        migrations.AddField(
            model_name='lieferungsposition',
            name='kundenart',
            field=models.CharField(blank=True, max_length=200, verbose_name='Kundenart'),
        ),
        migrations.AddField(
            model_name='lieferungsposition',
            name='lieferart',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lieferart'),
        ),
        migrations.AddField(
            model_name='lieferungsposition',
            name='loeschen',
            field=models.CharField(blank=True, max_length=50, verbose_name='Löschen'),
        ),
        migrations.AddField(
            model_name='lieferungsposition',
            name='logistikkosten_geraet_fw',
            field=models.CharField(blank=True, max_length=100, verbose_name='Logistikkosten Gerät FW'),
        ),
        migrations.AddField(
            model_name='lieferungsposition',
            name='menge_broker',
            field=models.CharField(blank=True, max_length=50, verbose_name='Menge Broker'),
        ),
        migrations.AddField(
            model_name='lieferungsposition',
            name='menge_marketplace',
            field=models.CharField(blank=True, max_length=50, verbose_name='Menge Marketplace'),
        ),
        migrations.AddField(
            model_name='lieferungsposition',
            name='menge_recycling',
            field=models.CharField(blank=True, max_length=50, verbose_name='Menge Recycling'),
        ),
        migrations.AddField(
            model_name='lieferungsposition',
            name='menge_reserve',
            field=models.CharField(blank=True, max_length=50, verbose_name='Menge Reserve'),
        ),
        migrations.AddField(
            model_name='lieferungsposition',
            name='menge_retail',
            field=models.CharField(blank=True, max_length=50, verbose_name='Menge Retail'),
        ),
        migrations.AddField(
            model_name='lieferungsposition',
            name='putzen',
            field=models.CharField(blank=True, max_length=50, verbose_name='Putzen'),
        ),
        migrations.AddField(
            model_name='lieferungsposition',
            name='securaze_moeglich',
            field=models.CharField(blank=True, max_length=50, verbose_name='Securaze möglich'),
        ),
        migrations.AddField(
            model_name='lieferungsposition',
            name='testen',
            field=models.CharField(blank=True, max_length=50, verbose_name='Testen'),
        ),
        migrations.AddField(
            model_name='lieferungsposition',
            name='verpackung',
            field=models.CharField(blank=True, max_length=50, verbose_name='Verpackung'),
        ),
        migrations.AddField(
            model_name='lieferungsposition',
            name='verpackungskosten',
            field=models.CharField(blank=True, max_length=100, verbose_name='Verpackungskosten'),
        ),
        migrations.AddField(
            model_name='lieferungsposition',
            name='versanddienstleister',
            field=models.CharField(blank=True, max_length=100, verbose_name='Versanddienstleister'),
        ),
        migrations.AddField(
            model_name='lieferungsposition',
            name='vk_netto_geraet',
            field=models.CharField(blank=True, max_length=100, verbose_name='VK netto Gerät'),
        ),
        migrations.AddField(
            model_name='lieferungsposition',
            name='waehrung',
            field=models.CharField(blank=True, max_length=50, verbose_name='Währung'),
        ),
        migrations.AddField(
            model_name='lieferungsposition',
            name='waehrungskurs',
            field=models.CharField(blank=True, max_length=50, verbose_name='Währungskurs'),
        ),
        migrations.AddField(
            model_name='lieferungsposition',
            name='wkz',
            field=models.CharField(blank=True, max_length=100, verbose_name='WKZ'),
        ),
        migrations.AlterField(
            model_name='lieferung',
            name='confirmed_menge',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Bestätigte Menge'),
        ),
    ]
