# Generated by Django 5.2.3 on 2025-07-08 19:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_alter_lieferung_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieferung',
            name='bestelldatum',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Bestelldatum'),
        ),
    ]
