# Generated by Django 5.2.3 on 2025-07-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_alter_lieferung_bestelldatum'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieferung',
            name='kommentar',
            field=models.TextField(blank=True, verbose_name='Kommentar'),
        ),
        migrations.AlterField(
            model_name='lieferung',
            name='bestelldatum',
            field=models.DateField(verbose_name='Bestelldatum'),
        ),
        migrations.AlterField(
            model_name='lieferung',
            name='erwartetes_datum',
            field=models.DateField(blank=True, null=True, verbose_name='Erwartetes Ankunftsdatum'),
        ),
    ]
